tls:
  certificates:
    - certFile: /home/dev/certs/hermes.local.pem
      keyFile: /home/dev/certs/hermes.local-key.pem
  options:
    mtls:
      clientAuth:
        caFiles:
          - /root/.step/certs/root_ca.crt
          - /root/.step/certs/intermediate_ca.crt
        clientAuthType: RequireAndVerifyClientCert
http:
  routers:
    app1:
      rule: "Host(`hermes.local`)"
      entryPoints: [websecure]
      service: app1-svc
      tls:
        options: mtls
    app2-plain:
      rule: "Host(`enroll.local`)"
      entryPoints: [web]
      service: app2-svc
    redirect-https:
      rule: "Host(`hermes.local`)"
      entryPoints: [web]
      middlewares: [redirect-https-mw]
      service: noop@internal
  middlewares:
    redirect-https-mw:
      redirectScheme:
        scheme: https
        permanent: true
  services:
    app1-svc:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://127.0.0.1:9119"
    app2-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://127.0.0.1:9120"
